;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_fill
	.import		_memcpy
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_clear_vram_buffer
	.import		_get_pad_new
	.import		_set_scroll_y
	.import		_get_ppu_addr
	.import		_set_data_pointer
	.import		_set_mt_pointer
	.import		_buffer_4_mt
	.import		_flush_vram_update2
	.export		_perrystandright_data
	.export		_perrystandleft_data
	.export		_perrywalkright0_data
	.export		_perrywalkright1_data
	.export		_perrywalkright2_data
	.export		_perrywalkleft0_data
	.export		_perrywalkleft1_data
	.export		_perrywalkleft2_data
	.export		_perrywalkdown0_data
	.export		_perrywalkdown1_data
	.export		_perrywalkdown2_data
	.export		_perrywalkup0_data
	.export		_perrywalkup1_data
	.export		_perrywalkup2_data
	.export		_nudeman_data
	.export		_Duck_data
	.export		_switchleft_data
	.export		_switchright_data
	.export		_lighton_data
	.export		_lightoff_data
	.export		_rock_data
	.export		_perryflag0_data
	.export		_perryflag1_data
	.export		_perryflag2_data
	.export		_blankflag0_data
	.export		_blankflag1_data
	.export		_blankflag2_data
	.export		_titletailwag0_data
	.export		_titletailwag1_data
	.export		_titletailwag2_data
	.export		_GoalFlag
	.export		_pad1
	.export		_pad1_new
	.export		_pad2
	.export		_pad2_new
	.export		_collision
	.export		_collision_L
	.export		_collision_R
	.export		_collision_U
	.export		_collision_D
	.export		_level
	.export		_p_maps
	.export		_coordinates
	.export		_temp1
	.export		_temp2
	.export		_temp3
	.export		_temp4
	.export		_temp_x
	.export		_temp_y
	.export		_game_mode
	.export		_show_text
	.export		_has_moved
	.export		_is_moving
	.export		_player_moved_frames
	.export		_local_left
	.export		_local_right
	.export		_local_up
	.export		_local_down
	.export		_pointer2
	.export		_address
	.export		_x
	.export		_y
	.export		_index
	.export		_index2
	.export		_c_map
	.export		_BoxGuy1
	.export		_Level1_0
	.export		_Level2_0
	.export		_Level3_0
	.export		_Level4_0
	.export		_Level_List
	.export		_level_text
	.export		_level_text_length
	.export		_level_player_x
	.export		_level_player_y
	.export		_level_goal_x
	.export		_level_goal_y
	.export		_palette_perrypuzzlesprites_a
	.export		_palette_perrytileset_a
	.export		_metatiles
	.export		_draw_bg
	.export		_draw_sprites
	.export		_movement
	.export		_bg_collision
	.export		_check_start
	.export		_sprite_collision
	.export		_level_up
	.export		_init_level_text
	.export		_set_direction
	.export		_draw_player_sprite
	.export		_init_mode_title
	.export		_main

.segment	"DATA"

_index:
	.byte	$00
_BoxGuy1:
	.byte	$40
	.byte	$50
	.byte	$0D
	.byte	$0E
	.byte	$00

.segment	"RODATA"

_perrystandright_data:
	.byte	$07
	.byte	$02
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$41
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$50
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$51
	.byte	$01
	.byte	$80
_perrystandleft_data:
	.byte	$01
	.byte	$02
	.byte	$30
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$41
	.byte	$08
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$50
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$51
	.byte	$41
	.byte	$80
_perrywalkright0_data:
	.byte	$07
	.byte	$02
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$41
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$54
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$55
	.byte	$01
	.byte	$80
_perrywalkright1_data:
	.byte	$07
	.byte	$02
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$41
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$52
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$53
	.byte	$01
	.byte	$80
_perrywalkright2_data:
	.byte	$07
	.byte	$02
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$41
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$56
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$57
	.byte	$01
	.byte	$80
_perrywalkleft0_data:
	.byte	$01
	.byte	$02
	.byte	$30
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$54
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$55
	.byte	$41
	.byte	$80
_perrywalkleft1_data:
	.byte	$01
	.byte	$02
	.byte	$30
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$52
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$53
	.byte	$41
	.byte	$80
_perrywalkleft2_data:
	.byte	$01
	.byte	$02
	.byte	$30
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$56
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$57
	.byte	$41
	.byte	$80
_perrywalkdown0_data:
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$60
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$61
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$72
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$73
	.byte	$01
	.byte	$80
_perrywalkdown1_data:
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$60
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$61
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$70
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$71
	.byte	$01
	.byte	$80
_perrywalkdown2_data:
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$60
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$61
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$74
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$75
	.byte	$01
	.byte	$80
_perrywalkup0_data:
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$90
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$93
	.byte	$01
	.byte	$80
_perrywalkup1_data:
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$90
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$91
	.byte	$01
	.byte	$80
_perrywalkup2_data:
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$92
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$91
	.byte	$01
	.byte	$80
_nudeman_data:
	.byte	$08
	.byte	$00
	.byte	$0D
	.byte	$01
	.byte	$10
	.byte	$00
	.byte	$0E
	.byte	$01
	.byte	$10
	.byte	$00
	.byte	$0F
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$1D
	.byte	$01
	.byte	$10
	.byte	$08
	.byte	$1E
	.byte	$01
	.byte	$10
	.byte	$08
	.byte	$1F
	.byte	$01
	.byte	$10
	.byte	$10
	.byte	$2E
	.byte	$01
	.byte	$18
	.byte	$10
	.byte	$2F
	.byte	$01
	.byte	$10
	.byte	$18
	.byte	$3E
	.byte	$01
	.byte	$10
	.byte	$18
	.byte	$3F
	.byte	$01
	.byte	$10
	.byte	$20
	.byte	$4E
	.byte	$01
	.byte	$18
	.byte	$20
	.byte	$4F
	.byte	$01
	.byte	$18
	.byte	$18
	.byte	$3F
	.byte	$01
	.byte	$08
	.byte	$10
	.byte	$2D
	.byte	$01
	.byte	$00
	.byte	$10
	.byte	$2C
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$1C
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$0C
	.byte	$01
	.byte	$08
	.byte	$18
	.byte	$3D
	.byte	$01
	.byte	$08
	.byte	$20
	.byte	$4D
	.byte	$01
	.byte	$08
	.byte	$28
	.byte	$5D
	.byte	$01
	.byte	$10
	.byte	$28
	.byte	$5E
	.byte	$01
	.byte	$08
	.byte	$30
	.byte	$6D
	.byte	$01
	.byte	$10
	.byte	$30
	.byte	$6E
	.byte	$01
	.byte	$18
	.byte	$30
	.byte	$6F
	.byte	$01
	.byte	$18
	.byte	$38
	.byte	$7F
	.byte	$01
	.byte	$10
	.byte	$38
	.byte	$7E
	.byte	$01
	.byte	$08
	.byte	$38
	.byte	$7D
	.byte	$01
	.byte	$00
	.byte	$38
	.byte	$7C
	.byte	$01
	.byte	$00
	.byte	$30
	.byte	$6C
	.byte	$01
	.byte	$80
_Duck_data:
	.byte	$08
	.byte	$00
	.byte	$BD
	.byte	$01
	.byte	$10
	.byte	$00
	.byte	$BE
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$CD
	.byte	$01
	.byte	$10
	.byte	$08
	.byte	$CE
	.byte	$01
	.byte	$18
	.byte	$08
	.byte	$CF
	.byte	$01
	.byte	$18
	.byte	$10
	.byte	$DF
	.byte	$01
	.byte	$10
	.byte	$10
	.byte	$DE
	.byte	$01
	.byte	$08
	.byte	$10
	.byte	$DD
	.byte	$01
	.byte	$00
	.byte	$10
	.byte	$DC
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$CC
	.byte	$01
	.byte	$00
	.byte	$18
	.byte	$EC
	.byte	$01
	.byte	$08
	.byte	$18
	.byte	$ED
	.byte	$01
	.byte	$10
	.byte	$18
	.byte	$EE
	.byte	$01
	.byte	$18
	.byte	$18
	.byte	$EF
	.byte	$01
	.byte	$18
	.byte	$20
	.byte	$FF
	.byte	$01
	.byte	$10
	.byte	$20
	.byte	$FE
	.byte	$01
	.byte	$08
	.byte	$20
	.byte	$FD
	.byte	$01
	.byte	$00
	.byte	$20
	.byte	$FC
	.byte	$01
	.byte	$80
_switchleft_data:
	.byte	$00
	.byte	$00
	.byte	$C0
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$D0
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$D1
	.byte	$00
	.byte	$80
_switchright_data:
	.byte	$08
	.byte	$00
	.byte	$C0
	.byte	$40
	.byte	$08
	.byte	$08
	.byte	$D0
	.byte	$40
	.byte	$00
	.byte	$08
	.byte	$D1
	.byte	$40
	.byte	$80
_lighton_data:
	.byte	$00
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$A3
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$B2
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$B3
	.byte	$00
	.byte	$80
_lightoff_data:
	.byte	$00
	.byte	$00
	.byte	$C2
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$C3
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$D2
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$D3
	.byte	$00
	.byte	$80
_rock_data:
	.byte	$00
	.byte	$00
	.byte	$E0
	.byte	$02
	.byte	$08
	.byte	$00
	.byte	$E1
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$F0
	.byte	$02
	.byte	$08
	.byte	$08
	.byte	$F1
	.byte	$02
	.byte	$80
_perryflag0_data:
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$80
_perryflag1_data:
	.byte	$00
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$80
_perryflag2_data:
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$80
_blankflag0_data:
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$80
_blankflag1_data:
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$80
_blankflag2_data:
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$80
_titletailwag0_data:
	.byte	$00
	.byte	$00
	.byte	$15
	.byte	$01
	.byte	$80
_titletailwag1_data:
	.byte	$00
	.byte	$00
	.byte	$17
	.byte	$01
	.byte	$80
_titletailwag2_data:
	.byte	$00
	.byte	$00
	.byte	$16
	.byte	$01
	.byte	$80
_GoalFlag:
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$12
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$13
	.byte	$00
	.byte	$80
_Level1_0:
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$34
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$33
	.byte	$35
	.byte	$04
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$04
	.byte	$0A
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$26
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$07
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$0A
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$0A
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$4B
	.byte	$00
	.byte	$07
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$09
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$00
	.byte	$36
	.byte	$39
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$38
_Level2_0:
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$34
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$31
	.byte	$33
	.byte	$35
	.byte	$04
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$04
	.byte	$0A
	.byte	$00
	.byte	$04
	.byte	$3A
	.byte	$26
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$0A
	.byte	$3B
	.byte	$4B
	.byte	$36
	.byte	$35
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$0A
	.byte	$00
	.byte	$06
	.byte	$21
	.byte	$04
	.byte	$22
	.byte	$3C
	.byte	$00
	.byte	$3A
	.byte	$22
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$3A
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$00
	.byte	$3A
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$07
	.byte	$3C
	.byte	$3A
	.byte	$3C
	.byte	$3A
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$3A
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$21
	.byte	$3A
	.byte	$04
	.byte	$3A
	.byte	$21
	.byte	$21
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3B
	.byte	$07
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$3C
	.byte	$3B
	.byte	$04
	.byte	$3B
	.byte	$07
	.byte	$3A
	.byte	$07
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$3B
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$0A
	.byte	$21
	.byte	$3A
	.byte	$04
	.byte	$3A
	.byte	$00
	.byte	$3B
	.byte	$00
	.byte	$3A
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3A
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$3C
	.byte	$3A
	.byte	$00
	.byte	$3C
	.byte	$3C
	.byte	$3B
	.byte	$0A
	.byte	$3A
	.byte	$25
	.byte	$08
	.byte	$22
	.byte	$3C
	.byte	$07
	.byte	$36
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$3C
	.byte	$09
	.byte	$0A
	.byte	$00
	.byte	$3A
	.byte	$00
	.byte	$3C
	.byte	$00
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$36
	.byte	$35
	.byte	$07
	.byte	$00
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3B
	.byte	$00
	.byte	$22
	.byte	$08
	.byte	$3B
	.byte	$07
	.byte	$07
	.byte	$00
	.byte	$36
	.byte	$39
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$38
_Level3_0:
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$83
	.byte	$65
	.byte	$1C
	.byte	$00
	.byte	$1E
	.byte	$1F
	.byte	$2B
	.byte	$83
	.byte	$65
	.byte	$1C
	.byte	$0E
	.byte	$1D
	.byte	$0F
	.byte	$0C
	.byte	$0F
	.byte	$83
	.byte	$0E
	.byte	$83
	.byte	$65
	.byte	$1C
	.byte	$0E
	.byte	$0C
	.byte	$1F
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$0D
	.byte	$00
	.byte	$00
	.byte	$1C
	.byte	$0E
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$1C
	.byte	$00
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$1F
	.byte	$00
	.byte	$2B
	.byte	$2A
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$1F
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$2B
	.byte	$4B
	.byte	$2A
	.byte	$00
	.byte	$1B
	.byte	$00
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$1D
	.byte	$1E
	.byte	$0C
	.byte	$0C
	.byte	$1F
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$21
	.byte	$1D
	.byte	$1C
	.byte	$00
	.byte	$1D
	.byte	$1C
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$0C
	.byte	$0C
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$1F
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$0F
	.byte	$1C
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$00
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$0E
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$0C
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$0C
	.byte	$00
	.byte	$00
	.byte	$83
	.byte	$00
	.byte	$1D
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0C
	.byte	$0F
	.byte	$1C
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0D
	.byte	$0C
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$1C
	.byte	$1D
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$0D
	.byte	$1F
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$1C
	.byte	$0E
	.byte	$0C
	.byte	$00
	.byte	$2A
	.byte	$1D
	.byte	$0C
	.byte	$1F
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$0C
	.byte	$0F
	.byte	$2B
	.byte	$83
	.byte	$65
	.byte	$1D
	.byte	$0F
	.byte	$1D
	.byte	$65
	.byte	$00
	.byte	$0E
	.byte	$0C
	.byte	$0E
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$1D
	.byte	$00
	.byte	$1C
	.byte	$00
	.byte	$83
	.byte	$65
	.byte	$00
	.byte	$1C
_Level4_0:
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$0A
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$0A
	.byte	$00
	.byte	$3B
	.byte	$3A
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$3A
	.byte	$3B
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$08
	.byte	$01
	.byte	$06
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3A
	.byte	$3A
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$3E
	.byte	$3E
	.byte	$3E
	.byte	$3E
	.byte	$25
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$3C
	.byte	$00
	.byte	$00
	.byte	$26
	.byte	$3F
	.byte	$3E
	.byte	$3E
	.byte	$3E
	.byte	$00
	.byte	$21
	.byte	$08
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$0A
	.byte	$00
	.byte	$2B
	.byte	$1A
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$06
	.byte	$06
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$01
	.byte	$07
	.byte	$1A
	.byte	$2B
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$06
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3D
	.byte	$3E
	.byte	$3D
	.byte	$3D
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$3A
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$26
	.byte	$3F
	.byte	$3E
	.byte	$3D
	.byte	$3E
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3B
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$09
	.byte	$08
	.byte	$3B
	.byte	$3A
	.byte	$07
	.byte	$00
	.byte	$4B
	.byte	$08
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$0A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3B
	.byte	$3B
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$07
_Level_List:
	.addr	_Level1_0
	.addr	_Level2_0
	.addr	_Level3_0
	.addr	_Level4_0
_level_text:
	.addr	L0631
	.addr	L0633
	.addr	L0635
	.addr	L0637
_level_text_length:
	.byte	$0B
	.byte	$0D
	.byte	$0B
	.byte	$10
_level_player_x:
	.byte	$40
	.byte	$3C
	.byte	$78
	.byte	$78
_level_player_y:
	.byte	$3C
	.byte	$3C
	.byte	$78
	.byte	$78
_level_goal_x:
	.byte	$B4
	.byte	$E1
	.byte	$B4
	.byte	$B4
_level_goal_y:
	.byte	$A0
	.byte	$1E
	.byte	$A0
	.byte	$A0
_palette_perrypuzzlesprites_a:
	.byte	$1A
	.byte	$30
	.byte	$0F
	.byte	$15
	.byte	$1A
	.byte	$11
	.byte	$21
	.byte	$20
	.byte	$1A
	.byte	$38
	.byte	$17
	.byte	$07
	.byte	$1A
	.byte	$0F
	.byte	$2D
	.byte	$3D
_palette_perrytileset_a:
	.byte	$1A
	.byte	$30
	.byte	$0F
	.byte	$15
	.byte	$1A
	.byte	$21
	.byte	$11
	.byte	$30
	.byte	$1A
	.byte	$38
	.byte	$17
	.byte	$07
	.byte	$1A
	.byte	$17
	.byte	$2A
	.byte	$0F
_metatiles:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$1E
	.byte	$1E
	.byte	$1F
	.byte	$1E
	.byte	$03
	.byte	$1E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$1E
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$03
	.byte	$1F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$1F
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$1F
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1F
	.byte	$03
	.byte	$1E
	.byte	$00
	.byte	$00
	.byte	$1F
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$0E
	.byte	$0E
	.byte	$0E
	.byte	$03
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$03
	.byte	$0E
	.byte	$0E
	.byte	$00
	.byte	$0E
	.byte	$03
	.byte	$0E
	.byte	$0E
	.byte	$0E
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1C
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$03
	.byte	$00
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$03
	.byte	$0E
	.byte	$00
	.byte	$0E
	.byte	$0E
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$8D
	.byte	$9D
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$9C
	.byte	$8D
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$7C
	.byte	$7D
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$7D
	.byte	$7E
	.byte	$03
	.byte	$9D
	.byte	$00
	.byte	$9C
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$8D
	.byte	$00
	.byte	$7E
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$A4
	.byte	$A5
	.byte	$B4
	.byte	$B5
	.byte	$02
	.byte	$A6
	.byte	$A7
	.byte	$B6
	.byte	$B7
	.byte	$02
	.byte	$A8
	.byte	$A9
	.byte	$B8
	.byte	$B9
	.byte	$02
	.byte	$C8
	.byte	$C9
	.byte	$D8
	.byte	$D9
	.byte	$02
	.byte	$C4
	.byte	$C5
	.byte	$D4
	.byte	$D5
	.byte	$02
	.byte	$C6
	.byte	$C7
	.byte	$D6
	.byte	$D7
	.byte	$02
	.byte	$E4
	.byte	$E5
	.byte	$F4
	.byte	$F5
	.byte	$02
	.byte	$E6
	.byte	$E7
	.byte	$F6
	.byte	$F7
	.byte	$02
	.byte	$E8
	.byte	$E9
	.byte	$F8
	.byte	$F9
	.byte	$02
	.byte	$8E
	.byte	$8F
	.byte	$9E
	.byte	$9F
	.byte	$03
	.byte	$9E
	.byte	$9F
	.byte	$8E
	.byte	$8F
	.byte	$03
	.byte	$AC
	.byte	$AD
	.byte	$BC
	.byte	$BD
	.byte	$03
	.byte	$84
	.byte	$85
	.byte	$94
	.byte	$95
	.byte	$02
	.byte	$86
	.byte	$87
	.byte	$96
	.byte	$97
	.byte	$02
	.byte	$88
	.byte	$89
	.byte	$98
	.byte	$99
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$E2
	.byte	$E3
	.byte	$F2
	.byte	$F3
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$12
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$11
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$02
	.byte	$AE
	.byte	$AF
	.byte	$BE
	.byte	$BF
	.byte	$00
	.byte	$C2
	.byte	$C3
	.byte	$D2
	.byte	$D3
	.byte	$03
	.byte	$C0
	.byte	$C1
	.byte	$D0
	.byte	$D1
	.byte	$02
	.byte	$8A
	.byte	$8B
	.byte	$9A
	.byte	$9B
	.byte	$02
	.byte	$8C
	.byte	$00
	.byte	$8C
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$AB
	.byte	$00
	.byte	$AB
	.byte	$02
	.byte	$CC
	.byte	$CD
	.byte	$DC
	.byte	$EE
	.byte	$02
	.byte	$CE
	.byte	$CE
	.byte	$EE
	.byte	$EE
	.byte	$02
	.byte	$CF
	.byte	$CD
	.byte	$EE
	.byte	$DD
	.byte	$02
	.byte	$CC
	.byte	$CE
	.byte	$DC
	.byte	$02
	.byte	$01
	.byte	$CF
	.byte	$CE
	.byte	$DE
	.byte	$DF
	.byte	$01
	.byte	$CF
	.byte	$CD
	.byte	$DE
	.byte	$FF
	.byte	$01
	.byte	$DC
	.byte	$DD
	.byte	$FE
	.byte	$FF
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$DC
	.byte	$EE
	.byte	$EC
	.byte	$EE
	.byte	$02
	.byte	$EE
	.byte	$EE
	.byte	$EE
	.byte	$EE
	.byte	$02
	.byte	$EE
	.byte	$ED
	.byte	$EE
	.byte	$DD
	.byte	$02
	.byte	$EC
	.byte	$DD
	.byte	$FE
	.byte	$ED
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$DC
	.byte	$ED
	.byte	$DC
	.byte	$DD
	.byte	$01
	.byte	$FE
	.byte	$ED
	.byte	$EC
	.byte	$DD
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$DC
	.byte	$EE
	.byte	$FC
	.byte	$DE
	.byte	$02
	.byte	$EE
	.byte	$EE
	.byte	$DF
	.byte	$DE
	.byte	$02
	.byte	$EE
	.byte	$DD
	.byte	$DF
	.byte	$FD
	.byte	$02
	.byte	$EC
	.byte	$DD
	.byte	$FC
	.byte	$DE
	.byte	$01
	.byte	$EF
	.byte	$CF
	.byte	$DF
	.byte	$DE
	.byte	$01
	.byte	$EF
	.byte	$ED
	.byte	$DE
	.byte	$FD
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$12
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$04
	.byte	$14
	.byte	$16
	.byte	$14
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$00
	.byte	$14
	.byte	$05
	.byte	$14
	.byte	$16
	.byte	$01
	.byte	$14
	.byte	$00
	.byte	$14
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$05
	.byte	$01
	.byte	$18
	.byte	$15
	.byte	$06
	.byte	$05
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$17
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$17
	.byte	$01
	.byte	$00
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$52
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$45
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$54
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$52
	.byte	$54
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$00
	.byte	$13
	.byte	$01
	.byte	$FA
	.byte	$00
	.byte	$12
	.byte	$1A
	.byte	$01
	.byte	$14
	.byte	$00
	.byte	$15
	.byte	$00
	.byte	$01
	.byte	$13
	.byte	$12
	.byte	$14
	.byte	$00
	.byte	$01
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$13
	.byte	$00
	.byte	$14
	.byte	$01
	.byte	$12
	.byte	$18
	.byte	$00
	.byte	$06
	.byte	$01
	.byte	$15
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$55
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$5A
	.byte	$5A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$45
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$55
	.byte	$45
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$53
	.byte	$54
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$00
	.byte	$16
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$00
	.byte	$06
	.byte	$12
	.byte	$01
	.byte	$14
	.byte	$00
	.byte	$16
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$14
	.byte	$00
	.byte	$14
	.byte	$01
	.byte	$14
	.byte	$00
	.byte	$14
	.byte	$00
	.byte	$01
	.byte	$0A
	.byte	$00
	.byte	$06
	.byte	$12
	.byte	$01
	.byte	$00
	.byte	$14
	.byte	$12
	.byte	$15
	.byte	$01
	.byte	$12
	.byte	$19
	.byte	$00
	.byte	$14
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$46
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$52
	.byte	$61
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$00
	.byte	$00
	.byte	$7F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$6C
	.byte	$42
	.byte	$72
	.byte	$00
	.byte	$61
	.byte	$6E
	.byte	$69
	.byte	$61
	.byte	$00
	.byte	$00
	.byte	$26
	.byte	$6E
	.byte	$00
	.byte	$00
L0C71:
	.byte	$50,$65,$72,$69,$70,$68,$65,$72,$61,$6C,$20,$50,$61,$6C,$61,$63
	.byte	$65,$00
L0637:
	.byte	$54,$77,$6F,$20,$50,$6C,$61,$79,$65,$72,$20,$47,$61,$6D,$65,$00
L0633:
	.byte	$4E,$6F,$74,$20,$73,$6F,$20,$73,$69,$6D,$70,$6C,$65,$00
L0C67:
	.byte	$46,$65,$72,$61,$6C,$20,$50,$65,$72,$72,$79,$27,$73,$00
L0635:
	.byte	$39,$30,$20,$44,$65,$67,$72,$65,$65,$73,$00
L0631:
	.byte	$45,$61,$73,$79,$20,$50,$65,$61,$73,$79,$00
L0C8F:
	.byte	$4C,$65,$76,$65,$6C,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_pad1:
	.res	1,$00
_pad1_new:
	.res	1,$00
_pad2:
	.res	1,$00
_pad2_new:
	.res	1,$00
_collision:
	.res	1,$00
_collision_L:
	.res	1,$00
_collision_R:
	.res	1,$00
_collision_U:
	.res	1,$00
_collision_D:
	.res	1,$00
_level:
	.res	1,$00
_p_maps:
	.res	2,$00
_coordinates:
	.res	1,$00
_temp1:
	.res	1,$00
_temp2:
	.res	1,$00
_temp3:
	.res	1,$00
_temp4:
	.res	1,$00
_temp_x:
	.res	1,$00
_temp_y:
	.res	1,$00
_game_mode:
	.res	1,$00
_show_text:
	.res	1,$00
_has_moved:
	.res	1,$00
_is_moving:
	.res	1,$00
_player_moved_frames:
	.res	1,$00
_local_left:
	.res	1,$00
_local_right:
	.res	1,$00
_local_up:
	.res	1,$00
_local_down:
	.res	1,$00
_pointer2:
	.res	2,$00
_address:
	.res	2,$00
_x:
	.res	1,$00
_y:
	.res	1,$00
_index2:
	.res	1,$00
.segment	"BSS"
_c_map:
	.res	240,$00

; ---------------------------------------------------------------
; void __near__ draw_bg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_bg: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; p_maps = Level_List[level];
;
	ldx     #$00
	lda     _level
	asl     a
	bcc     L0D55
	inx
	clc
L0D55:	adc     #<(_Level_List)
	sta     ptr1
	txa
	adc     #>(_Level_List)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     _p_maps+1
	dey
	lda     (ptr1),y
	sta     _p_maps
;
; memcpy(c_map, p_maps, 240);
;
	lda     #<(_c_map)
	ldx     #>(_c_map)
	jsr     pushax
	lda     _p_maps
	ldx     _p_maps+1
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jsr     _memcpy
;
; clear_vram_buffer();
;
	jsr     _clear_vram_buffer
;
; set_data_pointer(Level_List[level]);
;
	ldx     #$00
	lda     _level
	asl     a
	bcc     L0D56
	inx
	clc
L0D56:	adc     #<(_Level_List)
	sta     ptr1
	txa
	adc     #>(_Level_List)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _set_data_pointer
;
; set_mt_pointer(metatiles);
;
	lda     #<(_metatiles)
	ldx     #>(_metatiles)
	jsr     _set_mt_pointer
;
; for (y = 0;; y += 0x20)
;
	lda     #$00
L0D54:	sta     _y
;
; for (x = 0;; x += 0x20)
;
	lda     #$00
L0D53:	sta     _x
;
; address = get_ppu_addr(0, x, y);
;
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     _x
	dey
	sta     (sp),y
	lda     _y
	jsr     _get_ppu_addr
	sta     _address
	stx     _address+1
;
; index = (y & 0xf0) + (x >> 4);
;
	lda     _y
	and     #$F0
	sta     ptr1
	lda     _x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     ptr1
	sta     _index
;
; buffer_4_mt(address, index); // ppu_address, index to the data
;
	lda     _address
	ldx     _address+1
	jsr     pushax
	lda     _index
	jsr     _buffer_4_mt
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; if (x == 0xe0)
;
	lda     _x
	cmp     #$E0
;
; break;
;
	beq     L0D57
;
; for (x = 0;; x += 0x20)
;
	lda     #$20
	clc
	adc     _x
	jmp     L0D53
;
; if (y == 0xe0)
;
L0D57:	lda     _y
	cmp     #$E0
;
; break;
;
	beq     L0B97
;
; for (y = 0;; y += 0x20)
;
	lda     #$20
	clc
	adc     _y
	jmp     L0D54
;
; ppu_on_all(); // turn on screen
;
L0B97:	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprites: near

.segment	"CODE"

;
; oam_clear();
;
	jsr     _oam_clear
;
; draw_player_sprite();
;
	jsr     _draw_player_sprite
;
; oam_meta_spr(level_goal_x[level], level_goal_y[level], GoalFlag);
;
	jsr     decsp2
	ldy     _level
	lda     _level_goal_x,y
	ldy     #$01
	sta     (sp),y
	ldy     _level
	lda     _level_goal_y,y
	ldy     #$00
	sta     (sp),y
	lda     #<(_GoalFlag)
	ldx     #>(_GoalFlag)
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ movement (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_movement: near

.segment	"CODE"

;
; is_moving = 0;
;
	lda     #$00
	sta     _is_moving
;
; has_moved = 0;
;
	sta     _has_moved
;
; if (pad1 & local_left)
;
	lda     _local_left
	and     _pad1
	pha
	pla
	beq     L0D5A
;
; is_moving = 1;
;
	lda     #$01
	sta     _is_moving
;
; BoxGuy1.direction = LEFT;
;
	lda     #$00
	sta     _BoxGuy1+4
;
; BoxGuy1.X -= 1;
;
	dec     _BoxGuy1
;
; has_moved = 1;
;
	lda     #$01
;
; else if (pad1 & local_right)
;
	jmp     L0D58
L0D5A:	lda     _local_right
	and     _pad1
	pha
	pla
	beq     L0BD3
;
; is_moving = 1;
;
	lda     #$01
	sta     _is_moving
;
; BoxGuy1.direction = RIGHT;
;
	sta     _BoxGuy1+4
;
; BoxGuy1.X += 1;
;
	inc     _BoxGuy1
;
; has_moved = 1;
;
L0D58:	sta     _has_moved
;
; bg_collision();
;
L0BD3:	jsr     _bg_collision
;
; if (collision_R)
;
	lda     _collision_R
	beq     L0BDE
;
; BoxGuy1.X -= 1;
;
	dec     _BoxGuy1
;
; if (collision_L)
;
L0BDE:	lda     _collision_L
	beq     L0BE2
;
; BoxGuy1.X += 1;
;
	inc     _BoxGuy1
;
; if (pad1 & local_up && has_moved == 0)
;
L0BE2:	lda     _local_up
	and     _pad1
	pha
	pla
	beq     L0D5E
	lda     _has_moved
	bne     L0D5E
;
; BoxGuy1.direction = UP;
;
	lda     #$02
	sta     _BoxGuy1+4
;
; BoxGuy1.Y -= 1;
;
	dec     _BoxGuy1+1
;
; else if (pad1 & local_down && has_moved == 0)
;
	jmp     L0D63
L0D5E:	lda     _local_down
	and     _pad1
	pha
	pla
	beq     L0BF3
	lda     _has_moved
	bne     L0BF3
;
; BoxGuy1.direction = DOWN;
;
	lda     #$03
	sta     _BoxGuy1+4
;
; BoxGuy1.Y += 1;
;
	inc     _BoxGuy1+1
;
; has_moved = 1;
;
L0D63:	lda     #$01
	sta     _has_moved
;
; is_moving = 1;
;
	sta     _is_moving
;
; bg_collision();
;
L0BF3:	jsr     _bg_collision
;
; if (collision_D)
;
	lda     _collision_D
	beq     L0C00
;
; BoxGuy1.Y -= 1;
;
	dec     _BoxGuy1+1
;
; if (collision_U)
;
L0C00:	lda     _collision_U
	beq     L0C04
;
; BoxGuy1.Y += 1;
;
	inc     _BoxGuy1+1
;
; }
;
L0C04:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bg_collision (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bg_collision: near

.segment	"CODE"

;
; collision_L = 0;
;
	lda     #$00
	sta     _collision_L
;
; collision_R = 0;
;
	sta     _collision_R
;
; collision_U = 0;
;
	sta     _collision_U
;
; collision_D = 0; 
;
	sta     _collision_D
;
; temp_x = BoxGuy1.X; // left side
;
	lda     _BoxGuy1
	sta     _temp_x
;
; temp_y = BoxGuy1.Y; // top side
;
	lda     _BoxGuy1+1
	sta     _temp_y
;
; if (temp_y >= 0xf0)
;
	cmp     #$F0
;
; return;
;
	bcc     L0D6D
;
; }
;
	rts
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // upper left
;
L0D6D:	lda     _temp_x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0D66
;
; ++collision_L;
;
	inc     _collision_L
;
; ++collision_U;
;
	inc     _collision_U
;
; temp_x = BoxGuy1.X + BoxGuy1.width; // right side
;
L0D66:	lda     _BoxGuy1
	clc
	adc     _BoxGuy1+2
	sta     _temp_x
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // upper right
;
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0D67
;
; ++collision_R;
;
	inc     _collision_R
;
; ++collision_U;
;
	inc     _collision_U
;
; temp_y = BoxGuy1.Y + BoxGuy1.height; // bottom side
;
L0D67:	lda     _BoxGuy1+1
	clc
	adc     _BoxGuy1+3
	sta     _temp_y
;
; if (temp_y >= 0xf0)
;
	cmp     #$F0
;
; return;
;
	bcs     L0C55
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // bottom right
;
	lda     _temp_x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0D68
;
; ++collision_R;
;
	inc     _collision_R
;
; ++collision_D;
;
	inc     _collision_D
;
; temp_x = BoxGuy1.X; // left side
;
L0D68:	lda     _BoxGuy1
	sta     _temp_x
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // bottom left
;
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0C55
;
; ++collision_L;
;
	inc     _collision_L
;
; ++collision_D;
;
	inc     _collision_D
;
; }
;
L0C55:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ check_start (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_start: near

.segment	"CODE"

;
; if (pad1_new & PAD_START)
;
	lda     _pad1_new
	and     #$10
	beq     L0CAF
;
; ++level;
;
	inc     _level
;
; if (level >= 4)
;
	lda     _level
	cmp     #$04
	bcc     L0D6E
;
; level = 0;
;
	lda     #$00
	sta     _level
;
; game_mode = MODE_LEVEL_TITLE;
;
L0D6E:	lda     #$05
	sta     _game_mode
;
; init_level_text();
;
	jmp     _init_level_text
;
; }
;
L0CAF:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ sprite_collision (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite_collision: near

.segment	"CODE"

;
; if (BoxGuy1.X >= level_goal_x[level]-3 && BoxGuy1.X <= level_goal_x[level]+3
;
	lda     _BoxGuy1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_x,y
	sec
	sbc     #$03
	bcs     L0C0D
	ldx     #$FF
L0C0D:	jsr     tosicmp
	bcc     L0C0E
	lda     _BoxGuy1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_x,y
;
; && BoxGuy1.Y >= level_goal_y[level]-3 && BoxGuy1.Y <= level_goal_y[level]+3)
;
	clc
	adc     #$03
	bcc     L0C11
	ldx     #$01
L0C11:	jsr     tosicmp
	beq     L0D6F
	bcs     L0C0E
L0D6F:	lda     _BoxGuy1+1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_y,y
	sec
	sbc     #$03
	bcs     L0C14
	ldx     #$FF
L0C14:	jsr     tosicmp
	bcc     L0C0E
	lda     _BoxGuy1+1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_y,y
	clc
	adc     #$03
	bcc     L0C17
	ldx     #$01
L0C17:	jsr     tosicmp
	bcc     L0C0A
	beq     L0C0A
L0C0E:	rts
;
; level_up();
;
L0C0A:	jsr     _level_up
;
; show_text = 1;
;
	lda     #$01
	sta     _show_text
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ level_up (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_level_up: near

.segment	"CODE"

;
; ++level;
;
	inc     _level
;
; if (level >= 4)
;
	lda     _level
	cmp     #$04
	bcc     L0D70
;
; level = 0;
;
	lda     #$00
	sta     _level
;
; game_mode = MODE_LEVEL_TITLE;
;
L0D70:	lda     #$05
	sta     _game_mode
;
; init_level_text();
;
	jmp     _init_level_text

.endproc

; ---------------------------------------------------------------
; void __near__ init_level_text (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_level_text: near

.segment	"CODE"

;
; BoxGuy1.X = level_player_x[level];
;
	ldy     _level
	lda     _level_player_x,y
	sta     _BoxGuy1
;
; BoxGuy1.Y = level_player_y[level];
;
	ldy     _level
	lda     _level_player_y,y
	sta     _BoxGuy1+1
;
; oam_clear();
;
	jsr     _oam_clear
;
; ppu_off();
;
	jsr     _ppu_off
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_fill(0, 0x1000);
;
	lda     #$00
	jsr     pusha
	ldx     #$10
	jsr     _vram_fill
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; multi_vram_buffer_horz("Level", 5, NTADR_A(3,7));
;
	jsr     decsp3
	lda     #<(L0C8F)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C8F)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$E3
	jsr     _multi_vram_buffer_horz
;
; one_vram_buffer(49+level, NTADR_A(9,7));
;
	lda     _level
	clc
	adc     #$31
	jsr     pusha
	ldx     #$20
	lda     #$E9
	jsr     _one_vram_buffer
;
; multi_vram_buffer_horz(level_text[level], level_text_length[level], NTADR_A(3,10));
;
	jsr     decsp3
	ldx     #$00
	lda     _level
	asl     a
	bcc     L0D72
	inx
	clc
L0D72:	adc     #<(_level_text)
	sta     ptr1
	txa
	adc     #>(_level_text)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	iny
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     _level
	lda     _level_text_length,y
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$43
	jsr     _multi_vram_buffer_horz
;
; ppu_on_all();
;
	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ set_direction (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_direction: near

.segment	"CODE"

;
; local_up = PAD_UP;
;
	lda     #$08
	sta     _local_up
;
; local_down = PAD_DOWN;
;
	lda     #$04
	sta     _local_down
;
; local_left = PAD_LEFT;
;
	lda     #$02
	sta     _local_left
;
; local_right = PAD_RIGHT;
;
	lda     #$01
	sta     _local_right
;
; if(level == 2){
;
	lda     _level
	cmp     #$02
	bne     L0CC2
;
; local_up = PAD_LEFT;
;
	sta     _local_up
;
; local_down = PAD_RIGHT;
;
	lda     #$01
	sta     _local_down
;
; local_left = PAD_DOWN;
;
	lda     #$04
	sta     _local_left
;
; local_right = PAD_UP;
;
	lda     #$08
	sta     _local_right
;
; }
;
L0CC2:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_player_sprite (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player_sprite: near

.segment	"CODE"

;
; ++player_moved_frames;
;
	inc     _player_moved_frames
;
; if(player_moved_frames > 32){
;
	lda     _player_moved_frames
	cmp     #$21
	bcc     L0D78
;
; player_moved_frames = 0;
;
	lda     #$00
	sta     _player_moved_frames
;
; switch (BoxGuy1.direction)
;
L0D78:	lda     _BoxGuy1+4
;
; }
;
	beq     L0CD6
	cmp     #$01
	beq     L0CF3
	cmp     #$02
	jeq     L0D10
	cmp     #$03
	jeq     L0D2D
	jmp     L0D49
;
; if(is_moving) {
;
L0CD6:	lda     _is_moving
	beq     L0CD7
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L0D79
;
; pointer2 = perrywalkleft0_data;
;
	lda     #>(_perrywalkleft0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkleft0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L0D74
L0D79:	lda     _player_moved_frames
	cmp     #$10
	bcs     L0D7A
;
; pointer2 = perrywalkleft1_data;
;
	lda     #>(_perrywalkleft1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkleft1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L0D74
L0D7A:	lda     _player_moved_frames
	cmp     #$18
	bcs     L0D7B
;
; pointer2 = perrywalkleft2_data;
;
	lda     #>(_perrywalkleft2_data)
	sta     _pointer2+1
	lda     #<(_perrywalkleft2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L0D74
L0D7B:	lda     _player_moved_frames
	cmp     #$20
	bcs     L0CE8
;
; pointer2 = perrywalkleft1_data;
;
	lda     #>(_perrywalkleft1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkleft1_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrywalkleft0_data;
;
L0CE8:	lda     #>(_perrywalkleft0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkleft0_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrystandleft_data;
;
L0CD7:	lda     #>(_perrystandleft_data)
	sta     _pointer2+1
	lda     #<(_perrystandleft_data)
;
; break;
;
	jmp     L0D74
;
; if(is_moving) {
;
L0CF3:	lda     _is_moving
	jeq     L0D49
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L0D7C
;
; pointer2 = perrywalkright0_data;
;
	lda     #>(_perrywalkright0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkright0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L0D74
L0D7C:	lda     _player_moved_frames
	cmp     #$10
	bcs     L0D7D
;
; pointer2 = perrywalkright1_data;
;
	lda     #>(_perrywalkright1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkright1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L0D74
L0D7D:	lda     _player_moved_frames
	cmp     #$18
	bcs     L0D7E
;
; pointer2 = perrywalkright2_data;
;
	lda     #>(_perrywalkright2_data)
	sta     _pointer2+1
	lda     #<(_perrywalkright2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L0D74
L0D7E:	lda     _player_moved_frames
	cmp     #$20
	bcs     L0D05
;
; pointer2 = perrywalkright1_data;
;
	lda     #>(_perrywalkright1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkright1_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrywalkright0_data;
;
L0D05:	lda     #>(_perrywalkright0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkright0_data)
;
; } else {
;
	jmp     L0D74
;
; if(is_moving) {
;
L0D10:	lda     _is_moving
	beq     L0D11
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L0D7F
;
; pointer2 = perrywalkup0_data;
;
	lda     #>(_perrywalkup0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkup0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L0D74
L0D7F:	lda     _player_moved_frames
	cmp     #$10
	bcs     L0D80
;
; pointer2 = perrywalkup1_data;
;
	lda     #>(_perrywalkup1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkup1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L0D74
L0D80:	lda     _player_moved_frames
	cmp     #$18
	bcs     L0D81
;
; pointer2 = perrywalkup2_data;
;
	lda     #>(_perrywalkup2_data)
	sta     _pointer2+1
	lda     #<(_perrywalkup2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L0D74
L0D81:	lda     _player_moved_frames
	cmp     #$20
	bcs     L0D22
;
; pointer2 = perrywalkup1_data;
;
	lda     #>(_perrywalkup1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkup1_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrywalkup0_data;
;
L0D22:	lda     #>(_perrywalkup0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkup0_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrywalkup0_data;
;
L0D11:	lda     #>(_perrywalkup0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkup0_data)
;
; break;
;
	jmp     L0D74
;
; if(is_moving) {
;
L0D2D:	lda     _is_moving
	beq     L0D2E
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L0D82
;
; pointer2 = perrywalkdown0_data;
;
	lda     #>(_perrywalkdown0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkdown0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L0D74
L0D82:	lda     _player_moved_frames
	cmp     #$10
	bcs     L0D83
;
; pointer2 = perrywalkdown1_data;
;
	lda     #>(_perrywalkdown1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkdown1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L0D74
L0D83:	lda     _player_moved_frames
	cmp     #$18
	bcs     L0D84
;
; pointer2 = perrywalkdown2_data;
;
	lda     #>(_perrywalkdown2_data)
	sta     _pointer2+1
	lda     #<(_perrywalkdown2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L0D74
L0D84:	lda     _player_moved_frames
	cmp     #$20
	bcs     L0D3F
;
; pointer2 = perrywalkdown1_data;
;
	lda     #>(_perrywalkdown1_data)
	sta     _pointer2+1
	lda     #<(_perrywalkdown1_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrywalkdown0_data;
;
L0D3F:	lda     #>(_perrywalkdown0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkdown0_data)
;
; } else {
;
	jmp     L0D74
;
; pointer2 = perrywalkdown0_data;
;
L0D2E:	lda     #>(_perrywalkdown0_data)
	sta     _pointer2+1
	lda     #<(_perrywalkdown0_data)
;
; break;
;
	jmp     L0D74
;
; pointer2 = perrystandright_data;
;
L0D49:	lda     #>(_perrystandright_data)
	sta     _pointer2+1
	lda     #<(_perrystandright_data)
L0D74:	sta     _pointer2
;
; oam_meta_spr(BoxGuy1.X, BoxGuy1.Y, pointer2);
;
	jsr     decsp2
	lda     _BoxGuy1
	ldy     #$01
	sta     (sp),y
	lda     _BoxGuy1+1
	dey
	sta     (sp),y
	lda     _pointer2
	ldx     _pointer2+1
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_title (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_title: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; multi_vram_buffer_horz("Feral Perry's", 13, NTADR_A(9,10));
;
	jsr     decsp3
	lda     #<(L0C67)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C67)
	sta     (sp),y
	lda     #$0D
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$49
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz("Peripheral Palace", 17, NTADR_A(7,12));
;
	jsr     decsp3
	lda     #<(L0C71)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C71)
	sta     (sp),y
	lda     #$11
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$87
	jsr     _multi_vram_buffer_horz
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; game_mode = MODE_TITLE;
;
	lda     #$00
	sta     _game_mode
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; pal_bg(palette_perrytileset_a);
;
	lda     #<(_palette_perrytileset_a)
	ldx     #>(_palette_perrytileset_a)
	jsr     _pal_bg
;
; pal_spr(palette_perrypuzzlesprites_a);  
;
	lda     #<(_palette_perrypuzzlesprites_a)
	ldx     #>(_palette_perrypuzzlesprites_a)
	jsr     _pal_spr
;
; bank_spr(1);
;
	lda     #$01
	jsr     _bank_spr
;
; set_scroll_y(0xff); // shift the bg down 1 pixel
;
	ldx     #$00
	lda     #$FF
	jsr     _set_scroll_y
;
; set_vram_buffer();
;
	jsr     _set_vram_buffer
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; init_mode_title();
;
	jsr     _init_mode_title
;
; if (game_mode == MODE_TITLE)
;
L0D88:	lda     _game_mode
	bne     L0D89
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	beq     L0D88
;
; level = 0; //debug this value
;
	lda     #$00
	sta     _level
;
; init_level_text();
;
	jsr     _init_level_text
;
; game_mode = MODE_LEVEL_TITLE;
;
	lda     #$05
	sta     _game_mode
;
; else if (game_mode == MODE_GAME_OVER)
;
	jmp     L0D88
L0D89:	lda     _game_mode
	cmp     #$07
	bne     L0D8A
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	beq     L0D88
;
; game_mode = MODE_GAME;
;
	lda     #$01
	sta     _game_mode
;
; else if (game_mode == MODE_LEVEL_SELECT)
;
	jmp     L0D88
L0D8A:	lda     _game_mode
	cmp     #$06
	bne     L0D8B
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	beq     L0D88
;
; game_mode = MODE_GAME;
;
	lda     #$01
	sta     _game_mode
;
; else if (game_mode == MODE_LEVEL_TITLE)
;
	jmp     L0D88
L0D8B:	lda     _game_mode
	cmp     #$05
	bne     L0D8C
;
; oam_clear();
;
	jsr     _oam_clear
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	jeq     L0D88
;
; game_mode = MODE_GAME;
;
	lda     #$01
	sta     _game_mode
;
; draw_bg(); 
;
	jsr     _draw_bg
;
; set_direction();
;
	jsr     _set_direction
;
; else if (game_mode == MODE_GAME)
;
	jmp     L0D88
L0D8C:	lda     _game_mode
	cmp     #$01
	bne     L0D8D
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; if(level == 3){
;
	lda     _level
	cmp     #$03
	bne     L0B71
;
; pad1 = pad_poll(1);     // read the first controller
;
	lda     #$01
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(1); // newly pressed button. do pad_poll first
;
	lda     #$01
;
; } else {
;
	jmp     L0D8E
;
; pad1 = pad_poll(0);     // read the first controller
;
L0B71:	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0); // newly pressed button. do pad_poll first
;
	lda     #$00
L0D8E:	jsr     _get_pad_new
	sta     _pad1_new
;
; movement();
;
	jsr     _movement
;
; sprite_collision();
;
	jsr     _sprite_collision
;
; draw_sprites();
;
	jsr     _draw_sprites
;
; check_start();
;
	jsr     _check_start
;
; else
;
	jmp     L0D88
;
; game_mode = MODE_TITLE;
;
L0D8D:	lda     #$00
	sta     _game_mode
;
; while (1)
;
	jmp     L0D88

.endproc

