;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_put
	.import		_vram_fill
	.import		_memcpy
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_get_pad_new
	.import		_set_scroll_y
	.export		__perrystandright_data
	.export		__perrystandleft_data
	.export		__perrywalright0_data
	.export		__perrywalkright1_data
	.export		__perrywalkright2_data
	.export		__perrywalkleft0_data
	.export		__perrywalkleft1_data
	.export		__perrywalkleft2_data
	.export		__perrywalkdown0_data
	.export		__perrywalkdown1_data
	.export		__perrywalkdown2_data
	.export		__perrywalkup0_data
	.export		__perrywalkup1_data
	.export		__perrywalkup2_data
	.export		_GoalFlag
	.export		_pad1
	.export		_pad1_new
	.export		_pad2
	.export		_pad2_new
	.export		_collision
	.export		_collision_L
	.export		_collision_R
	.export		_collision_U
	.export		_collision_D
	.export		_level
	.export		_p_maps
	.export		_coordinates
	.export		_temp1
	.export		_temp2
	.export		_temp3
	.export		_temp4
	.export		_temp_x
	.export		_temp_y
	.export		_game_mode
	.export		_show_text
	.export		_has_moved
	.export		_is_moving
	.export		_player_moved_frames
	.export		_local_left
	.export		_local_right
	.export		_local_up
	.export		_local_down
	.export		_pointer2
	.export		_c_map
	.export		_BoxGuy1
	.export		_c1
	.export		_c2
	.export		_c3
	.export		_c4
	.export		_All_Collision_Maps
	.export		_level_text
	.export		_level_text_length
	.export		_level_player_x
	.export		_level_player_y
	.export		_level_goal_x
	.export		_level_goal_y
	.export		_palette_bg
	.export		_palette_sp
	.export		_draw_bg
	.export		_draw_sprites
	.export		_movement
	.export		_bg_collision
	.export		_check_start
	.export		_sprite_collision
	.export		_level_up
	.export		_init_level_text
	.export		_set_direction
	.export		_draw_player_sprite
	.export		_main

.segment	"DATA"

_BoxGuy1:
	.byte	$40
	.byte	$50
	.byte	$0F
	.byte	$0E
	.byte	$00

.segment	"RODATA"

__perrystandright_data:
	.byte	$07
	.byte	$02
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$51
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$60
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$61
	.byte	$01
	.byte	$80
__perrystandleft_data:
	.byte	$01
	.byte	$02
	.byte	$40
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$50
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$60
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$61
	.byte	$41
	.byte	$80
__perrywalright0_data:
	.byte	$07
	.byte	$02
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$51
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$66
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$67
	.byte	$01
	.byte	$80
__perrywalkright1_data:
	.byte	$07
	.byte	$02
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$51
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$62
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$63
	.byte	$01
	.byte	$80
__perrywalkright2_data:
	.byte	$07
	.byte	$02
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$51
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$64
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$65
	.byte	$01
	.byte	$80
__perrywalkleft0_data:
	.byte	$01
	.byte	$02
	.byte	$40
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$50
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$66
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$67
	.byte	$41
	.byte	$80
__perrywalkleft1_data:
	.byte	$01
	.byte	$02
	.byte	$40
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$50
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$62
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$63
	.byte	$41
	.byte	$80
__perrywalkleft2_data:
	.byte	$01
	.byte	$02
	.byte	$40
	.byte	$40
	.byte	$08
	.byte	$00
	.byte	$50
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$41
	.byte	$08
	.byte	$08
	.byte	$64
	.byte	$41
	.byte	$00
	.byte	$08
	.byte	$65
	.byte	$41
	.byte	$80
__perrywalkdown0_data:
	.byte	$02
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$72
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$73
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$82
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$83
	.byte	$01
	.byte	$80
__perrywalkdown1_data:
	.byte	$02
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$71
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$80
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$81
	.byte	$01
	.byte	$80
__perrywalkdown2_data:
	.byte	$02
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$74
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$75
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$84
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$85
	.byte	$01
	.byte	$80
__perrywalkup0_data:
	.byte	$00
	.byte	$00
	.byte	$92
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$93
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$A2
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$A3
	.byte	$01
	.byte	$80
__perrywalkup1_data:
	.byte	$00
	.byte	$00
	.byte	$90
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$91
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$A0
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$A1
	.byte	$01
	.byte	$80
__perrywalkup2_data:
	.byte	$00
	.byte	$00
	.byte	$94
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$95
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$A4
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$A5
	.byte	$01
	.byte	$80
_GoalFlag:
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$12
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$13
	.byte	$00
	.byte	$80
_c1:
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
_c2:
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
_c3:
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
_c4:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_All_Collision_Maps:
	.addr	_c1
	.addr	_c2
	.addr	_c3
	.addr	_c4
_level_text:
	.addr	L04F8
	.addr	L04FA
	.addr	L04FC
	.addr	L04FE
_level_text_length:
	.byte	$0B
	.byte	$0D
	.byte	$0B
	.byte	$10
_level_player_x:
	.byte	$40
	.byte	$3C
	.byte	$78
	.byte	$78
_level_player_y:
	.byte	$3C
	.byte	$3C
	.byte	$78
	.byte	$78
_level_goal_x:
	.byte	$B4
	.byte	$E1
	.byte	$B4
	.byte	$B4
_level_goal_y:
	.byte	$A0
	.byte	$1E
	.byte	$A0
	.byte	$A0
_palette_bg:
	.byte	$0A
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_palette_sp:
	.byte	$0F
	.byte	$30
	.byte	$0F
	.byte	$15
	.byte	$0F
	.byte	$11
	.byte	$21
	.byte	$20
	.byte	$0F
	.byte	$38
	.byte	$17
	.byte	$07
	.byte	$0F
	.byte	$1A
	.byte	$2A
	.byte	$17
L054D:
	.byte	$50,$65,$72,$69,$70,$68,$65,$72,$61,$6C,$20,$50,$61,$6C,$61,$63
	.byte	$65,$00
L04FE:
	.byte	$54,$77,$6F,$20,$50,$6C,$61,$79,$65,$72,$20,$47,$61,$6D,$65,$00
L04FA:
	.byte	$4E,$6F,$74,$20,$73,$6F,$20,$73,$69,$6D,$70,$6C,$65,$00
L0543:
	.byte	$46,$65,$72,$61,$6C,$20,$50,$65,$72,$72,$79,$27,$73,$00
L04FC:
	.byte	$39,$30,$20,$44,$65,$67,$72,$65,$65,$73,$00
L04F8:
	.byte	$45,$61,$73,$79,$20,$50,$65,$61,$73,$79,$00
L06B6:
	.byte	$4C,$65,$76,$65,$6C,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_pad1:
	.res	1,$00
_pad1_new:
	.res	1,$00
_pad2:
	.res	1,$00
_pad2_new:
	.res	1,$00
_collision:
	.res	1,$00
_collision_L:
	.res	1,$00
_collision_R:
	.res	1,$00
_collision_U:
	.res	1,$00
_collision_D:
	.res	1,$00
_level:
	.res	1,$00
_p_maps:
	.res	2,$00
_coordinates:
	.res	1,$00
_temp1:
	.res	1,$00
_temp2:
	.res	1,$00
_temp3:
	.res	1,$00
_temp4:
	.res	1,$00
_temp_x:
	.res	1,$00
_temp_y:
	.res	1,$00
_game_mode:
	.res	1,$00
_show_text:
	.res	1,$00
_has_moved:
	.res	1,$00
_is_moving:
	.res	1,$00
_player_moved_frames:
	.res	1,$00
_local_left:
	.res	1,$00
_local_right:
	.res	1,$00
_local_up:
	.res	1,$00
_local_down:
	.res	1,$00
_pointer2:
	.res	2,$00
.segment	"BSS"
_c_map:
	.res	240,$00

; ---------------------------------------------------------------
; void __near__ draw_bg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_bg: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; p_maps = All_Collision_Maps[level];
;
	ldx     #$00
	lda     _level
	asl     a
	bcc     L077C
	inx
	clc
L077C:	adc     #<(_All_Collision_Maps)
	sta     ptr1
	txa
	adc     #>(_All_Collision_Maps)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     _p_maps+1
	dey
	lda     (ptr1),y
	sta     _p_maps
;
; memcpy(c_map, p_maps, 240);
;
	lda     #<(_c_map)
	ldx     #>(_c_map)
	jsr     pushax
	lda     _p_maps
	ldx     _p_maps+1
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jsr     _memcpy
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for (temp_y = 0; temp_y < 15; ++temp_y)
;
	lda     #$00
	sta     _temp_y
L077D:	lda     _temp_y
	cmp     #$0F
	bcs     L05C0
;
; for (temp_x = 0; temp_x < 16; ++temp_x)
;
	lda     #$00
	sta     _temp_x
L077E:	lda     _temp_x
	cmp     #$10
	bcs     L0780
;
; temp1 = (temp_y << 4) + temp_x;
;
	lda     _temp_y
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     _temp_x
	sta     _temp1
;
; if (c_map[temp1])
;
	ldy     _temp1
	lda     _c_map,y
	beq     L077F
;
; vram_put(0x10); // wall
;
	lda     #$10
	jsr     _vram_put
;
; vram_put(0x10);
;
	lda     #$10
;
; else
;
	jmp     L077A
;
; vram_put(0); // blank
;
L077F:	jsr     _vram_put
;
; vram_put(0);
;
	lda     #$00
L077A:	jsr     _vram_put
;
; for (temp_x = 0; temp_x < 16; ++temp_x)
;
	inc     _temp_x
	jmp     L077E
;
; for (temp_x = 0; temp_x < 16; ++temp_x)
;
L0780:	lda     #$00
	sta     _temp_x
L0781:	lda     _temp_x
	cmp     #$10
	bcs     L0783
;
; temp1 = (temp_y << 4) + temp_x;
;
	lda     _temp_y
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     _temp_x
	sta     _temp1
;
; if (c_map[temp1])
;
	ldy     _temp1
	lda     _c_map,y
	beq     L0782
;
; vram_put(0x10); // wall
;
	lda     #$10
	jsr     _vram_put
;
; vram_put(0x10);
;
	lda     #$10
;
; else
;
	jmp     L077B
;
; vram_put(0); // blank
;
L0782:	jsr     _vram_put
;
; vram_put(0);
;
	lda     #$00
L077B:	jsr     _vram_put
;
; for (temp_x = 0; temp_x < 16; ++temp_x)
;
	inc     _temp_x
	jmp     L0781
;
; for (temp_y = 0; temp_y < 15; ++temp_y)
;
L0783:	inc     _temp_y
	jmp     L077D
;
; ppu_on_all(); // turn on screen
;
L05C0:	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprites: near

.segment	"CODE"

;
; oam_clear();
;
	jsr     _oam_clear
;
; draw_player_sprite();
;
	jsr     _draw_player_sprite
;
; oam_meta_spr(level_goal_x[level], level_goal_y[level], GoalFlag);
;
	jsr     decsp2
	ldy     _level
	lda     _level_goal_x,y
	ldy     #$01
	sta     (sp),y
	ldy     _level
	lda     _level_goal_y,y
	ldy     #$00
	sta     (sp),y
	lda     #<(_GoalFlag)
	ldx     #>(_GoalFlag)
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ movement (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_movement: near

.segment	"CODE"

;
; is_moving = 0;
;
	lda     #$00
	sta     _is_moving
;
; has_moved = 0;
;
	sta     _has_moved
;
; if (pad1 & local_left)
;
	lda     _local_left
	and     _pad1
	pha
	pla
	beq     L0786
;
; is_moving = 1;
;
	lda     #$01
	sta     _is_moving
;
; BoxGuy1.direction = LEFT;
;
	lda     #$00
	sta     _BoxGuy1+4
;
; BoxGuy1.X -= 1;
;
	dec     _BoxGuy1
;
; has_moved = 1;
;
	lda     #$01
;
; else if (pad1 & local_right)
;
	jmp     L0784
L0786:	lda     _local_right
	and     _pad1
	pha
	pla
	beq     L0613
;
; is_moving = 1;
;
	lda     #$01
	sta     _is_moving
;
; BoxGuy1.direction = RIGHT;
;
	sta     _BoxGuy1+4
;
; BoxGuy1.X += 1;
;
	inc     _BoxGuy1
;
; has_moved = 1;
;
L0784:	sta     _has_moved
;
; bg_collision();
;
L0613:	jsr     _bg_collision
;
; if (collision_R)
;
	lda     _collision_R
	beq     L061E
;
; BoxGuy1.X -= 1;
;
	dec     _BoxGuy1
;
; if (collision_L)
;
L061E:	lda     _collision_L
	beq     L0622
;
; BoxGuy1.X += 1;
;
	inc     _BoxGuy1
;
; if (pad1 & local_up && has_moved == 0)
;
L0622:	lda     _local_up
	and     _pad1
	pha
	pla
	beq     L078A
	lda     _has_moved
	bne     L078A
;
; BoxGuy1.direction = UP;
;
	lda     #$02
	sta     _BoxGuy1+4
;
; BoxGuy1.Y -= 1;
;
	dec     _BoxGuy1+1
;
; else if (pad1 & local_down && has_moved == 0)
;
	jmp     L078F
L078A:	lda     _local_down
	and     _pad1
	pha
	pla
	beq     L0633
	lda     _has_moved
	bne     L0633
;
; BoxGuy1.direction = DOWN;
;
	lda     #$03
	sta     _BoxGuy1+4
;
; BoxGuy1.Y += 1;
;
	inc     _BoxGuy1+1
;
; has_moved = 1;
;
L078F:	lda     #$01
	sta     _has_moved
;
; is_moving = 1;
;
	sta     _is_moving
;
; bg_collision();
;
L0633:	jsr     _bg_collision
;
; if (collision_D)
;
	lda     _collision_D
	beq     L0640
;
; BoxGuy1.Y -= 1;
;
	dec     _BoxGuy1+1
;
; if (collision_U)
;
L0640:	lda     _collision_U
	beq     L0644
;
; BoxGuy1.Y += 1;
;
	inc     _BoxGuy1+1
;
; }
;
L0644:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bg_collision (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bg_collision: near

.segment	"CODE"

;
; collision_L = 0;
;
	lda     #$00
	sta     _collision_L
;
; collision_R = 0;
;
	sta     _collision_R
;
; collision_U = 0;
;
	sta     _collision_U
;
; collision_D = 0;
;
	sta     _collision_D
;
; temp_x = BoxGuy1.X; // left side
;
	lda     _BoxGuy1
	sta     _temp_x
;
; temp_y = BoxGuy1.Y; // top side
;
	lda     _BoxGuy1+1
	sta     _temp_y
;
; if (temp_y >= 0xf0)
;
	cmp     #$F0
;
; return;
;
	bcc     L0799
;
; }
;
	rts
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // upper left
;
L0799:	lda     _temp_x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0792
;
; ++collision_L;
;
	inc     _collision_L
;
; ++collision_U;
;
	inc     _collision_U
;
; temp_x = BoxGuy1.X + BoxGuy1.width; // right side
;
L0792:	lda     _BoxGuy1
	clc
	adc     _BoxGuy1+2
	sta     _temp_x
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // upper right
;
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0793
;
; ++collision_R;
;
	inc     _collision_R
;
; ++collision_U;
;
	inc     _collision_U
;
; temp_y = BoxGuy1.Y + BoxGuy1.height; // bottom side
;
L0793:	lda     _BoxGuy1+1
	clc
	adc     _BoxGuy1+3
	sta     _temp_y
;
; if (temp_y >= 0xf0)
;
	cmp     #$F0
;
; return;
;
	bcs     L0695
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // bottom right
;
	lda     _temp_x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0794
;
; ++collision_R;
;
	inc     _collision_R
;
; ++collision_D;
;
	inc     _collision_D
;
; temp_x = BoxGuy1.X; // left side
;
L0794:	lda     _BoxGuy1
	sta     _temp_x
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0); // bottom left
;
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; if (c_map[coordinates])
;
	ldy     _coordinates
	lda     _c_map,y
	beq     L0695
;
; ++collision_L;
;
	inc     _collision_L
;
; ++collision_D;
;
	inc     _collision_D
;
; }
;
L0695:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ check_start (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_start: near

.segment	"CODE"

;
; if (pad1_new & PAD_START)
;
	lda     _pad1_new
	and     #$10
	beq     L06D6
;
; ++level;
;
	inc     _level
;
; if (level >= 4)
;
	lda     _level
	cmp     #$04
	bcc     L079A
;
; level = 0;
;
	lda     #$00
	sta     _level
;
; game_mode = MODE_LEVEL_TITLE;
;
L079A:	lda     #$05
	sta     _game_mode
;
; init_level_text();
;
	jmp     _init_level_text
;
; }
;
L06D6:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ sprite_collision (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite_collision: near

.segment	"CODE"

;
; if (BoxGuy1.X >= level_goal_x[level]-3 && BoxGuy1.X <= level_goal_x[level]+3
;
	lda     _BoxGuy1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_x,y
	sec
	sbc     #$03
	bcs     L064D
	ldx     #$FF
L064D:	jsr     tosicmp
	bcc     L064E
	lda     _BoxGuy1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_x,y
;
; && BoxGuy1.Y >= level_goal_y[level]-3 && BoxGuy1.Y <= level_goal_y[level]+3)
;
	clc
	adc     #$03
	bcc     L0651
	ldx     #$01
L0651:	jsr     tosicmp
	beq     L079B
	bcs     L064E
L079B:	lda     _BoxGuy1+1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_y,y
	sec
	sbc     #$03
	bcs     L0654
	ldx     #$FF
L0654:	jsr     tosicmp
	bcc     L064E
	lda     _BoxGuy1+1
	jsr     pusha0
	ldy     _level
	lda     _level_goal_y,y
	clc
	adc     #$03
	bcc     L0657
	ldx     #$01
L0657:	jsr     tosicmp
	bcc     L064A
	beq     L064A
L064E:	rts
;
; level_up();
;
L064A:	jsr     _level_up
;
; show_text = 1;
;
	lda     #$01
	sta     _show_text
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ level_up (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_level_up: near

.segment	"CODE"

;
; ++level;
;
	inc     _level
;
; if (level >= 4)
;
	lda     _level
	cmp     #$04
	bcc     L079C
;
; level = 0;
;
	lda     #$00
	sta     _level
;
; game_mode = MODE_LEVEL_TITLE;
;
L079C:	lda     #$05
	sta     _game_mode
;
; init_level_text();
;
	jmp     _init_level_text

.endproc

; ---------------------------------------------------------------
; void __near__ init_level_text (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_level_text: near

.segment	"CODE"

;
; BoxGuy1.X = level_player_x[level];
;
	ldy     _level
	lda     _level_player_x,y
	sta     _BoxGuy1
;
; BoxGuy1.Y = level_player_y[level];
;
	ldy     _level
	lda     _level_player_y,y
	sta     _BoxGuy1+1
;
; oam_clear();
;
	jsr     _oam_clear
;
; ppu_off();
;
	jsr     _ppu_off
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_fill(0, 0x1000);
;
	lda     #$00
	jsr     pusha
	ldx     #$10
	jsr     _vram_fill
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; multi_vram_buffer_horz("Level", 5, NTADR_A(3,7));
;
	jsr     decsp3
	lda     #<(L06B6)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L06B6)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$E3
	jsr     _multi_vram_buffer_horz
;
; one_vram_buffer(49+level, NTADR_A(9,7));
;
	lda     _level
	clc
	adc     #$31
	jsr     pusha
	ldx     #$20
	lda     #$E9
	jsr     _one_vram_buffer
;
; multi_vram_buffer_horz(level_text[level], level_text_length[level], NTADR_A(3,10));
;
	jsr     decsp3
	ldx     #$00
	lda     _level
	asl     a
	bcc     L079E
	inx
	clc
L079E:	adc     #<(_level_text)
	sta     ptr1
	txa
	adc     #>(_level_text)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	iny
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     _level
	lda     _level_text_length,y
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$43
	jsr     _multi_vram_buffer_horz
;
; ppu_on_all();
;
	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ set_direction (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_direction: near

.segment	"CODE"

;
; local_up = PAD_UP;
;
	lda     #$08
	sta     _local_up
;
; local_down = PAD_DOWN;
;
	lda     #$04
	sta     _local_down
;
; local_left = PAD_LEFT;
;
	lda     #$02
	sta     _local_left
;
; local_right = PAD_RIGHT;
;
	lda     #$01
	sta     _local_right
;
; if(level == 2){
;
	lda     _level
	cmp     #$02
	bne     L06E9
;
; local_up = PAD_LEFT;
;
	sta     _local_up
;
; local_down = PAD_RIGHT;
;
	lda     #$01
	sta     _local_down
;
; local_left = PAD_DOWN;
;
	lda     #$04
	sta     _local_left
;
; local_right = PAD_UP;
;
	lda     #$08
	sta     _local_right
;
; }
;
L06E9:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_player_sprite (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player_sprite: near

.segment	"CODE"

;
; ++player_moved_frames;
;
	inc     _player_moved_frames
;
; if(player_moved_frames > 32){
;
	lda     _player_moved_frames
	cmp     #$21
	bcc     L07A4
;
; player_moved_frames = 0;
;
	lda     #$00
	sta     _player_moved_frames
;
; switch (BoxGuy1.direction)
;
L07A4:	lda     _BoxGuy1+4
;
; }
;
	beq     L06FD
	cmp     #$01
	beq     L071A
	cmp     #$02
	jeq     L0737
	cmp     #$03
	jeq     L0754
	jmp     L0770
;
; if(is_moving) {
;
L06FD:	lda     _is_moving
	beq     L06FE
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L07A5
;
; pointer2 = _perrywalkleft0_data;
;
	lda     #>(__perrywalkleft0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkleft0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L07A0
L07A5:	lda     _player_moved_frames
	cmp     #$10
	bcs     L07A6
;
; pointer2 = _perrywalkleft1_data;
;
	lda     #>(__perrywalkleft1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkleft1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L07A0
L07A6:	lda     _player_moved_frames
	cmp     #$18
	bcs     L07A7
;
; pointer2 = _perrywalkleft2_data;
;
	lda     #>(__perrywalkleft2_data)
	sta     _pointer2+1
	lda     #<(__perrywalkleft2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L07A0
L07A7:	lda     _player_moved_frames
	cmp     #$20
	bcs     L070F
;
; pointer2 = _perrywalkleft1_data;
;
	lda     #>(__perrywalkleft1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkleft1_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrywalkleft0_data;
;
L070F:	lda     #>(__perrywalkleft0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkleft0_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrystandleft_data;
;
L06FE:	lda     #>(__perrystandleft_data)
	sta     _pointer2+1
	lda     #<(__perrystandleft_data)
;
; break;
;
	jmp     L07A0
;
; if(is_moving) {
;
L071A:	lda     _is_moving
	jeq     L0770
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L07A8
;
; pointer2 = _perrywalright0_data;
;
	lda     #>(__perrywalright0_data)
	sta     _pointer2+1
	lda     #<(__perrywalright0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L07A0
L07A8:	lda     _player_moved_frames
	cmp     #$10
	bcs     L07A9
;
; pointer2 = _perrywalkright1_data;
;
	lda     #>(__perrywalkright1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkright1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L07A0
L07A9:	lda     _player_moved_frames
	cmp     #$18
	bcs     L07AA
;
; pointer2 = _perrywalkright2_data;
;
	lda     #>(__perrywalkright2_data)
	sta     _pointer2+1
	lda     #<(__perrywalkright2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L07A0
L07AA:	lda     _player_moved_frames
	cmp     #$20
	bcs     L072C
;
; pointer2 = _perrywalkright1_data;
;
	lda     #>(__perrywalkright1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkright1_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrywalright0_data;
;
L072C:	lda     #>(__perrywalright0_data)
	sta     _pointer2+1
	lda     #<(__perrywalright0_data)
;
; } else {
;
	jmp     L07A0
;
; if(is_moving) {
;
L0737:	lda     _is_moving
	beq     L0738
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L07AB
;
; pointer2 = _perrywalkup0_data;
;
	lda     #>(__perrywalkup0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkup0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L07A0
L07AB:	lda     _player_moved_frames
	cmp     #$10
	bcs     L07AC
;
; pointer2 = _perrywalkup1_data;
;
	lda     #>(__perrywalkup1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkup1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L07A0
L07AC:	lda     _player_moved_frames
	cmp     #$18
	bcs     L07AD
;
; pointer2 = _perrywalkup2_data;
;
	lda     #>(__perrywalkup2_data)
	sta     _pointer2+1
	lda     #<(__perrywalkup2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L07A0
L07AD:	lda     _player_moved_frames
	cmp     #$20
	bcs     L0749
;
; pointer2 = _perrywalkup1_data;
;
	lda     #>(__perrywalkup1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkup1_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrywalkup0_data;
;
L0749:	lda     #>(__perrywalkup0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkup0_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrywalkup0_data;
;
L0738:	lda     #>(__perrywalkup0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkup0_data)
;
; break;
;
	jmp     L07A0
;
; if(is_moving) {
;
L0754:	lda     _is_moving
	beq     L0755
;
; if(player_moved_frames < 8){
;
	lda     _player_moved_frames
	cmp     #$08
	bcs     L07AE
;
; pointer2 = _perrywalkdown0_data;
;
	lda     #>(__perrywalkdown0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkdown0_data)
;
; } else if(player_moved_frames < 16){
;
	jmp     L07A0
L07AE:	lda     _player_moved_frames
	cmp     #$10
	bcs     L07AF
;
; pointer2 = _perrywalkdown1_data;
;
	lda     #>(__perrywalkdown1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkdown1_data)
;
; } else if(player_moved_frames < 24) {
;
	jmp     L07A0
L07AF:	lda     _player_moved_frames
	cmp     #$18
	bcs     L07B0
;
; pointer2 = _perrywalkdown2_data;
;
	lda     #>(__perrywalkdown2_data)
	sta     _pointer2+1
	lda     #<(__perrywalkdown2_data)
;
; } else if(player_moved_frames < 32) {
;
	jmp     L07A0
L07B0:	lda     _player_moved_frames
	cmp     #$20
	bcs     L0766
;
; pointer2 = _perrywalkdown1_data;
;
	lda     #>(__perrywalkdown1_data)
	sta     _pointer2+1
	lda     #<(__perrywalkdown1_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrywalkdown0_data;
;
L0766:	lda     #>(__perrywalkdown0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkdown0_data)
;
; } else {
;
	jmp     L07A0
;
; pointer2 = _perrywalkdown0_data;
;
L0755:	lda     #>(__perrywalkdown0_data)
	sta     _pointer2+1
	lda     #<(__perrywalkdown0_data)
;
; break;
;
	jmp     L07A0
;
; pointer2 = _perrystandright_data;
;
L0770:	lda     #>(__perrystandright_data)
	sta     _pointer2+1
	lda     #<(__perrystandright_data)
L07A0:	sta     _pointer2
;
; oam_meta_spr(BoxGuy1.X, BoxGuy1.Y, pointer2);
;
	jsr     decsp2
	lda     _BoxGuy1
	ldy     #$01
	sta     (sp),y
	lda     _BoxGuy1+1
	dey
	sta     (sp),y
	lda     _pointer2
	ldx     _pointer2+1
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; pal_bg(palette_bg);
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; pal_spr(palette_sp);  
;
	lda     #<(_palette_sp)
	ldx     #>(_palette_sp)
	jsr     _pal_spr
;
; bank_spr(1);
;
	lda     #$01
	jsr     _bank_spr
;
; set_scroll_y(0xff); // shift the bg down 1 pixel
;
	ldx     #$00
	lda     #$FF
	jsr     _set_scroll_y
;
; set_vram_buffer();
;
	jsr     _set_vram_buffer
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; ppu_off();
;
	jsr     _ppu_off
;
; multi_vram_buffer_horz("Feral Perry's", 13, NTADR_A(9,10));
;
	jsr     decsp3
	lda     #<(L0543)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0543)
	sta     (sp),y
	lda     #$0D
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$49
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz("Peripheral Palace", 17, NTADR_A(7,12));
;
	jsr     decsp3
	lda     #<(L054D)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L054D)
	sta     (sp),y
	lda     #$11
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$87
	jsr     _multi_vram_buffer_horz
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; game_mode = MODE_TITLE;
;
L07BC:	lda     #$00
L07B3:	sta     _game_mode
;
; if (game_mode == MODE_TITLE)
;
L07B5:	lda     _game_mode
	bne     L07B6
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	beq     L07B5
;
; level = 0; //debug this value
;
	lda     #$00
	sta     _level
;
; init_level_text();
;
	jsr     _init_level_text
;
; game_mode = MODE_LEVEL_TITLE;
;
	lda     #$05
;
; else if (game_mode == MODE_GAME_OVER)
;
	jmp     L07B3
L07B6:	lda     _game_mode
	cmp     #$07
	bne     L07B7
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	beq     L07B5
;
; game_mode = MODE_GAME;
;
	lda     #$01
;
; else if (game_mode == MODE_LEVEL_SELECT)
;
	jmp     L07B3
L07B7:	lda     _game_mode
	cmp     #$06
	bne     L07B8
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	beq     L07B5
;
; game_mode = MODE_GAME;
;
	lda     #$01
;
; else if (game_mode == MODE_LEVEL_TITLE)
;
	jmp     L07B3
L07B8:	lda     _game_mode
	cmp     #$05
	bne     L07B9
;
; oam_clear();
;
	jsr     _oam_clear
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)
;
	and     #$10
	jeq     L07B5
;
; game_mode = MODE_GAME;
;
	lda     #$01
	sta     _game_mode
;
; draw_bg(); 
;
	jsr     _draw_bg
;
; set_direction();
;
	jsr     _set_direction
;
; else if (game_mode == MODE_GAME)
;
	jmp     L07B5
L07B9:	lda     _game_mode
	cmp     #$01
	jne     L07BC
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; if(level == 3){
;
	lda     _level
	cmp     #$03
	bne     L059E
;
; pad1 = pad_poll(1);     // read the first controller
;
	lda     #$01
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(1); // newly pressed button. do pad_poll first
;
	lda     #$01
;
; } else {
;
	jmp     L07BB
;
; pad1 = pad_poll(0);     // read the first controller
;
L059E:	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0); // newly pressed button. do pad_poll first
;
	lda     #$00
L07BB:	jsr     _get_pad_new
	sta     _pad1_new
;
; movement();
;
	jsr     _movement
;
; sprite_collision();
;
	jsr     _sprite_collision
;
; draw_sprites();
;
	jsr     _draw_sprites
;
; check_start();
;
	jsr     _check_start
;
; else
;
	jmp     L07B5

.endproc

