;this file for FamiTone2 library generated by text2data tool

nes_perry_puzzler_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env4,@env0,@env6
	.byte $00
	.byte $b0 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env0,@env7
	.byte $00
	.byte $30 ;instrument $05
	.word @env5,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ce,$00,$00
@env2:
	.byte $c8,$ce,$cd,$ca,$c9,$02,$c8,$c7,$c6,$02,$c5,$02,$c4,$c4,$c3,$c3
	.byte $c2,$02,$c1,$c1,$c0,$00,$14
@env3:
	.byte $c6,$cf,$cf,$c9,$c6,$c3,$c0,$00,$06
@env4:
	.byte $cd,$cf,$cc,$cb,$ca,$c9,$00,$05
@env5:
	.byte $ce,$cc,$ca,$c9,$c7,$c5,$c3,$c0,$00,$07
@env6:
	.byte $c8,$c0,$03,$c0,$00,$00
@env7:
	.byte $b8,$80,$00,$01


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $f9,$85
@ref1:
	.byte $f9,$85
@ref2:
	.byte $f9,$85
@ref3:
	.byte $f9,$85
@ref4:
	.byte $f9,$85
@ref5:
	.byte $f9,$85
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $83,$84,$37,$3c,$89,$2b,$32,$89,$39,$40,$89,$2d,$32,$89,$3d,$45
	.byte $34,$85,$31,$37,$3e,$85,$39,$41,$48,$85,$2d,$32,$85
@ref9:
	.byte $83,$2b,$33,$3a,$85,$37,$3c,$89,$29,$2f,$36,$85,$33,$38,$89,$3d
	.byte $45,$34,$85,$31,$37,$3e,$85,$39,$41,$49,$25,$2d,$33,$3a,$81
@ref10:
	.byte $83,$37,$3c,$89,$2b,$32,$89,$39,$40,$89,$2d,$32,$89,$3d,$45,$34
	.byte $85,$31,$37,$3e,$85,$39,$41,$48,$85,$2d,$32,$85
@ref11:
	.byte $83,$2b,$33,$3a,$85,$37,$3c,$89,$29,$2f,$36,$85,$33,$39,$40,$85
	.byte $3d,$45,$34,$85,$31,$37,$3f,$32,$85,$3c,$85,$46,$8d
@ref12:
	.byte $2d,$31,$3f,$37,$37,$3f,$31,$2d,$3b,$37,$43,$31,$3b,$37,$31,$37
	.byte $2f,$35,$3d,$43,$3d,$43,$3d,$35,$2f,$39,$35,$41,$39,$41,$35,$2e
	.byte $81
@ref13:
	.byte $2d,$33,$3b,$33,$37,$3f,$45,$35,$2b,$3f,$39,$33,$35,$31,$3d,$43
	.byte $41,$29,$2f,$37,$1b,$2f,$3b,$41,$3f,$34,$85,$3e,$85,$31,$30,$85
	.byte $ff,$1c
	.word @ref10
	.byte $ff,$1f
	.word @ref9
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $82,$2e,$8d,$28,$8d,$32,$8d,$24,$8d,$36,$8d,$28,$8d,$32,$8d,$24
	.byte $8d
@ref17:
	.byte $3c,$8d,$2e,$8d,$38,$8d,$2a,$8d,$36,$8d,$28,$8d,$32,$8d,$24,$8d
@ref18:
	.byte $2e,$8d,$28,$8d,$32,$8d,$24,$8d,$36,$8d,$28,$8d,$32,$8d,$24,$8d
@ref19:
	.byte $3c,$8d,$2e,$8d,$38,$8d,$2a,$8d,$36,$8d,$28,$8d,$1a,$85,$24,$85
	.byte $2e,$8d
@ref20:
	.byte $30,$8d,$30,$8d,$3a,$8d,$3a,$8d,$2e,$8d,$2e,$8d,$38,$8d,$38,$8d
@ref21:
	.byte $2c,$8d,$36,$8d,$2a,$8d,$34,$8d,$28,$8d,$32,$8d,$26,$8d,$30,$8d
	.byte $ff,$10
	.word @ref18
	.byte $ff,$10
	.word @ref17
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $86,$20,$85,$88,$16,$85,$16,$85,$16,$85,$86,$20,$8d,$20,$85,$88
	.byte $16,$85,$86,$20,$85,$88,$16,$8d,$17,$17,$86,$20,$89,$21,$88,$16
	.byte $85,$16,$85
@ref25:
	.byte $86,$20,$85,$88,$16,$85,$16,$85,$16,$85,$86,$20,$8d,$20,$85,$88
	.byte $16,$85,$86,$20,$85,$88,$16,$8d,$16,$85,$86,$20,$8d,$88,$16,$85
	.byte $16,$85
	.byte $ff,$1b
	.word @ref24
	.byte $ff,$1a
	.word @ref25
@ref28:
	.byte $86,$20,$85,$88,$16,$85,$86,$20,$85,$88,$16,$85,$86,$20,$85,$88
	.byte $16,$85,$86,$21,$88,$17,$17,$17,$86,$20,$85,$88,$16,$85,$86,$20
	.byte $85,$88,$16,$85,$86,$21,$20,$85,$88,$17,$86,$20,$85,$88,$17,$86
	.byte $20,$81
@ref29:
	.byte $20,$85,$88,$17,$17,$86,$21,$88,$17,$16,$85,$86,$20,$85,$88,$16
	.byte $85,$86,$20,$85,$88,$16,$85,$86,$20,$85,$88,$16,$85,$86,$20,$85
	.byte $88,$16,$85,$86,$20,$85,$88,$17,$86,$21,$88,$17,$86,$21,$88,$16
	.byte $85
	.byte $ff,$1b
	.word @ref24
	.byte $ff,$1a
	.word @ref25
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $f9,$85
@ref33:
	.byte $f9,$85
@ref34:
	.byte $f9,$85
@ref35:
	.byte $f9,$85
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f9,$85
@ref38:
	.byte $f9,$85
@ref39:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref40:
	.byte $f9,$85
@ref41:
	.byte $f9,$85
@ref42:
	.byte $f9,$85
@ref43:
	.byte $f9,$85
@ref44:
	.byte $f9,$85
@ref45:
	.byte $f9,$85
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref46:
	.byte $84,$32,$8d,$32,$8d,$36,$8d,$36,$8d,$36,$8d,$40,$8d,$32,$8d,$36
	.byte $85,$40,$85
@ref47:
	.byte $32,$8d,$32,$8d,$36,$8d,$36,$8d,$36,$8d,$40,$8d,$32,$8d,$40,$85
	.byte $33,$32,$81
@ref48:
	.byte $24,$8d,$24,$8d,$24,$8d,$24,$8d,$36,$8d,$36,$8d,$36,$8d,$28,$85
	.byte $28,$85
	.byte $ff,$12
	.word @ref48
@ref50:
	.byte $32,$8d,$32,$8d,$36,$8d,$36,$8d,$36,$8d,$40,$8d,$32,$8d,$36,$85
	.byte $40,$85
	.byte $ff,$12
	.word @ref50
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref52:
	.byte $84,$52,$85,$58,$85,$5c,$85,$52,$85,$36,$85,$3e,$85,$44,$85,$5d
	.byte $63,$4e,$85,$54,$85,$4e,$85,$54,$85,$58,$85,$5c,$85,$55,$5d,$55
	.byte $4e,$81
@ref53:
	.byte $4b,$4f,$53,$59,$53,$4f,$4b,$4f,$4f,$53,$57,$5d,$57,$53,$4e,$85
	.byte $54,$85,$54,$85,$40,$85,$40,$85,$4a,$85,$58,$85,$40,$85,$33,$32
	.byte $81
@ref54:
	.byte $3d,$45,$4b,$45,$3b,$45,$3d,$3b,$3d,$45,$4b,$45,$4b,$4b,$45,$3b
	.byte $37,$3f,$45,$41,$3f,$3b,$37,$3b,$37,$3d,$3b,$3d,$4f,$49,$43,$48
	.byte $81
	.byte $ff,$21
	.word @ref54
@ref56:
	.byte $52,$85,$58,$85,$5c,$85,$52,$85,$36,$85,$3e,$85,$44,$85,$5d,$63
	.byte $4e,$85,$54,$85,$4e,$85,$54,$85,$58,$85,$5c,$85,$55,$5d,$55,$4e
	.byte $81
	.byte $ff,$21
	.word @ref56
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref58:
	.byte $88,$1c,$95,$1d,$86,$03,$88,$1c,$95,$1d,$86,$03,$88,$1c,$95,$1d
	.byte $86,$03,$88,$1c,$95,$1d,$86,$02,$81
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref58
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f9,$85
@ref66:
	.byte $f9,$85
@ref67:
	.byte $f9,$85
@ref68:
	.byte $f9,$85
@ref69:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$09
@song2ch0loop:
@ref70:
	.byte $97
@ref71:
	.byte $97
@ref72:
	.byte $97
@ref73:
	.byte $97
@ref74:
	.byte $97
@ref75:
	.byte $97
@ref76:
	.byte $97
@ref77:
	.byte $97
@ref78:
	.byte $97
@ref79:
	.byte $97
@ref80:
	.byte $97
@ref81:
	.byte $97
@ref82:
	.byte $97
@ref83:
	.byte $97
@ref84:
	.byte $97
@ref85:
	.byte $97
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref86:
	.byte $84,$4b,$44,$52,$44,$40,$3c,$4e,$4a,$4e,$44,$40
@ref87:
	.byte $3c,$83,$3c,$83,$3c,$83,$4e,$4a,$44
@ref88:
	.byte $40,$83,$47,$44,$40,$83,$4a,$52,$81
@ref89:
	.byte $52,$4a,$44,$40,$83,$4a,$49,$44,$40,$81
@ref90:
	.byte $3c,$40,$44,$85,$4e,$4a,$44,$4e,$83
@ref91:
	.byte $44,$4d,$53,$5a,$56,$4d,$53,$56
@ref92:
	.byte $48,$83,$4e,$57,$49,$44,$49,$42
@ref93:
	.byte $44,$83,$4c,$4e,$54,$58,$52,$4e,$4a,$4e,$52
@ref94:
	.byte $3d,$54,$52,$4b,$3c,$83,$4e,$4a,$4e
@ref95:
	.byte $3d,$44,$4a,$45,$3c,$50,$52,$58,$50,$58
@ref96:
	.byte $4e,$83,$4e,$57,$5c,$83,$4a,$56,$81
@ref97:
	.byte $46,$44,$40,$4e,$83,$40,$41,$46,$44,$40
@ref98:
	.byte $40,$83,$46,$4b,$5f,$58,$50,$83
@ref99:
	.byte $44,$46,$44,$44,$3d,$40,$83,$56,$4e,$81
@ref100:
	.byte $41,$46,$56,$4f,$59,$52,$4a,$83
@ref101:
	.byte $4b,$44,$4f,$4e,$4a,$83,$5e,$5c,$58
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref102:
	.byte $82,$24,$83,$32,$83,$24,$83,$36,$83
@ref103:
	.byte $24,$83,$3a,$83,$24,$83,$36,$83
@ref104:
	.byte $28,$83,$36,$83,$32,$83,$40,$83
@ref105:
	.byte $24,$83,$32,$83,$32,$83,$40,$83
@ref106:
	.byte $24,$83,$32,$83,$24,$83,$36,$83
@ref107:
	.byte $2c,$83,$3a,$83,$26,$83,$34,$83
@ref108:
	.byte $30,$83,$3e,$83,$22,$83,$30,$83
@ref109:
	.byte $2c,$83,$3a,$83,$32,$83,$40,$83
	.byte $ff,$08
	.word @ref106
@ref111:
	.byte $24,$83,$3a,$83,$25,$23,$20,$81
@ref112:
	.byte $1e,$83,$2c,$83,$1e,$83,$32,$83
@ref113:
	.byte $28,$83,$2e,$83,$36,$83,$2e,$83
@ref114:
	.byte $28,$83,$36,$83,$20,$83,$2e,$83
@ref115:
	.byte $24,$83,$32,$83,$28,$83,$36,$83
	.byte $ff,$08
	.word @ref104
@ref117:
	.byte $24,$83,$36,$83,$32,$83,$28,$83
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref118:
	.byte $86,$20,$83,$88,$16,$83,$86,$20,$83,$88,$16,$83
	.byte $ff,$08
	.word @ref118
	.byte $ff,$08
	.word @ref118
	.byte $ff,$08
	.word @ref118
@ref122:
	.byte $86,$20,$83,$88,$16,$83,$17,$16,$86,$20,$83
@ref123:
	.byte $88,$16,$83,$86,$20,$83,$88,$16,$83,$17,$16
@ref124:
	.byte $16,$83,$86,$20,$83,$88,$16,$83,$86,$21,$88,$16
@ref125:
	.byte $16,$83,$86,$20,$83,$88,$16,$83,$86,$21,$20
@ref126:
	.byte $20,$83,$88,$16,$83,$17,$16,$86,$20,$83
	.byte $ff,$08
	.word @ref123
	.byte $ff,$08
	.word @ref124
	.byte $ff,$08
	.word @ref125
@ref130:
	.byte $20,$83,$88,$16,$83,$86,$20,$83,$88,$16,$83
	.byte $ff,$08
	.word @ref118
	.byte $ff,$08
	.word @ref118
	.byte $ff,$08
	.word @ref118
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref134:
	.byte $97
@ref135:
	.byte $97
@ref136:
	.byte $97
@ref137:
	.byte $97
@ref138:
	.byte $97
@ref139:
	.byte $97
@ref140:
	.byte $97
@ref141:
	.byte $97
@ref142:
	.byte $97
@ref143:
	.byte $97
@ref144:
	.byte $97
@ref145:
	.byte $97
@ref146:
	.byte $97
@ref147:
	.byte $97
@ref148:
	.byte $97
@ref149:
	.byte $97
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$07
@song3ch0loop:
@ref150:
	.byte $bf
@ref151:
	.byte $bf
@ref152:
	.byte $bf
@ref153:
	.byte $bf
@ref154:
	.byte $bf
@ref155:
	.byte $bf
@ref156:
	.byte $bf
@ref157:
	.byte $bf
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref158:
	.byte $84,$59,$51,$4f,$5f,$57,$4f,$4b,$45,$55,$5b,$59,$55,$47,$43,$47
	.byte $4e,$81
@ref159:
	.byte $55,$59,$5b,$51,$46,$8d,$51,$59,$50,$95
@ref160:
	.byte $51,$4f,$4b,$47,$4b,$49,$45,$4e,$89,$5f,$58,$89,$55,$4e,$81
@ref161:
	.byte $47,$59,$54,$85,$50,$83,$4e,$54,$85,$5a,$83,$58,$4a,$85,$5b,$63
	.byte $5f,$5a,$81
@ref162:
	.byte $51,$59,$50,$85,$4f,$4e,$89,$4b,$43,$41,$3d,$47,$43,$4f,$54,$81
@ref163:
	.byte $43,$43,$3c,$91,$55,$4d,$47,$51,$4d,$5b,$55,$51,$4c,$81
@ref164:
	.byte $51,$58,$85,$4b,$4f,$55,$55,$4e,$89,$51,$4f,$44,$85,$56,$85
@ref165:
	.byte $85,$46,$4a,$83,$46,$43,$41,$3f,$51,$47,$44,$85,$5f,$5b,$5a,$54
	.byte $42,$46,$4e,$54
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref166:
	.byte $80,$20,$85,$2e,$85,$1e,$85,$2c,$85,$24,$85,$32,$85,$2e,$85,$3c
	.byte $85
@ref167:
	.byte $24,$85,$32,$85,$2e,$85,$3c,$85,$20,$85,$2e,$85,$21,$2f,$2b,$28
	.byte $81
@ref168:
	.byte $32,$85,$2e,$85,$2c,$85,$36,$85,$28,$85,$36,$85,$32,$85,$24,$85
@ref169:
	.byte $2e,$85,$3c,$85,$32,$85,$3c,$85,$2a,$85,$32,$85,$3c,$85,$2e,$85
@ref170:
	.byte $38,$85,$46,$85,$36,$85,$44,$85,$24,$85,$32,$85,$2e,$85,$3c,$85
@ref171:
	.byte $24,$85,$32,$85,$2e,$85,$3c,$85,$2e,$85,$24,$85,$2e,$85,$38,$85
@ref172:
	.byte $2a,$85,$38,$85,$36,$85,$28,$85,$32,$85,$40,$85,$2c,$85,$2a,$85
@ref173:
	.byte $28,$85,$32,$85,$24,$85,$2a,$85,$28,$85,$32,$85,$24,$85,$2e,$85
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref174:
	.byte $86,$20,$85,$88,$16,$85,$86,$20,$85,$88,$16,$85,$86,$20,$85,$88
	.byte $16,$85,$86,$20,$85,$88,$16,$85
	.byte $ff,$10
	.word @ref174
	.byte $ff,$10
	.word @ref174
	.byte $ff,$10
	.word @ref174
	.byte $ff,$10
	.word @ref174
	.byte $ff,$10
	.word @ref174
	.byte $ff,$10
	.word @ref174
	.byte $ff,$10
	.word @ref174
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref182:
	.byte $bf
@ref183:
	.byte $bf
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
@ref189:
	.byte $bf
	.byte $fd
	.word @song3ch4loop
